import { type DefaultTreeAdapterMap,
         parseFragment }
  from 'parse5';
import { BIND_PREFIX,
         CONTEXT_ATTR,
         createBindingSpec,
         isEventSuffix }
  from './binding-attribute.js';
import { createBuiltInPipes }
  from './pipes.js';
import { splitPath }
  from './read-model-path.js';
import { BindingSpec }
  from './types.js';

type ParsedNode = DefaultTreeAdapterMap['node'];

type ParsedElement = DefaultTreeAdapterMap['element'];

type ParsedTemplate = DefaultTreeAdapterMap['template'];

/** The first line of every generated module, which marks it as generated. */
export const GENERATED_HEADER =
  '// Generated by data-bind-compile';

const MODEL_ATTR = 'data-bind-model';

const PIPES_ATTR = 'data-bind-pipes';

const DEFAULT_RUNTIME_MODULE =
  'asljs-data-binding';

const IDENTIFIER =
  /^[A-Za-z_$][\w$]*$/;

export interface CompileTemplateOptions
{
  /** The template's file name, used in the generated comments and errors. */
  fileName: string;

  /** The module the generated code imports the runtime from. */
  runtimeModule?: string;
}

/**
 * A template that cannot be compiled, at the line and column it names.
 */
export class TemplateCompileError extends Error
{
  constructor(
    readonly reason: string,
    readonly fileName: string,
    readonly line: number,
    readonly column: number
  )
  {
    super(
      `${fileName}:${line}:${column}: ${reason}`);

    this.name =
      'TemplateCompileError';
  }
}

interface TypeReference
{
  specifier: string;
  name: string;
}

interface Emitter
{
  /** The template's base name, for the comments next to the generated module. */
  fileName: string;

  /** The template's path as given, for errors. */
  sourceName: string;

  lines: string[];
  usesAttributeValue: boolean;
  usesAction: boolean;
  usesPipeName: boolean;
  contexts: number;
}

/**
 * Compiles a `*.tpl.html` template to the source of its `*.tpl.ts` module.
 *
 * The file holds one `<template>` element. Its `data-bind-model` attribute
 * names the model type as `<module>#<type>`, and the optional
 * `data-bind-pipes` attribute names the type of the custom pipes the same way.
 * The module exports the markup, `createTemplate` and a typed `bindTemplate`,
 * and holds a function that is never called, with one statement per binding
 * that the TypeScript compiler checks against the model and element types.
 */
export function compileTemplate(
    source: string,
    options: CompileTemplateOptions
  ): string
{
  const fileName = options.fileName;

  const fragment =
    parseFragment(
      source,
      { sourceCodeLocationInfo: true });

  const templates =
    fragment.childNodes.filter(
      (node): node is ParsedTemplate =>
      isElement(node)
      && node.tagName === 'template');

  if (templates.length !== 1) {
    throw new TemplateCompileError(
      `Expect exactly one <template> element, found ${templates.length}.`,
      fileName,
      1,
      1);
  }

  const template = templates[0];

  const model =
    readTypeReference(
      template,
      MODEL_ATTR,
      fileName);

  if (model === null) {
    throw errorAt(
      template,
      undefined,
      fileName,
      `Expect the <template> to name its model type in ${MODEL_ATTR}="<module>#<type>".`);
  }

  const pipes =
    readTypeReference(
      template,
      PIPES_ATTR,
      fileName);

  const location =
    template.sourceCodeLocation;

  const html =
    location?.startTag && location.endTag
    ? source.slice(
      location.startTag.endOffset,
      location.endTag.startOffset)
    : '';

  const emitter: Emitter =
    { fileName:
        baseName(fileName),
      sourceName: fileName,
      lines: [ ],
      usesAttributeValue: false,
      usesAction: false,
      usesPipeName: false,
      contexts: 0 };

  emitChildren(
    template.content.childNodes,
    'model',
    1,
    emitter);

  return renderModule(
    { fileName:
        baseName(fileName),
      runtimeModule:
        options.runtimeModule
        ?? DEFAULT_RUNTIME_MODULE,
      model,
      pipes,
      html,
      emitter });
}

function readTypeReference(
    element: ParsedElement,
    name: string,
    fileName: string
  ): TypeReference | null
{
  const value =
    element.attrs.find(
      attribute => attribute.name === name)
    ?.value;

  if (value === undefined) {
    return null;
  }

  const hash =
    value.lastIndexOf('#');

  const specifier =
    value.slice(
      0,
      Math.max(
        hash,
        0)).trim();

  const typeName =
    value.slice(
      hash + 1).trim();

  if (
    hash < 0
    || specifier === ''
    || !IDENTIFIER.test(typeName)
  ) {
    throw errorAt(
      element,
      name,
      fileName,
      `Expect ${name} to be "<module>#<type>", got "${value}".`);
  }

  return { specifier,
           name: typeName };
}

function emitChildren(
    nodes: ParsedNode[],
    scope: string,
    depth: number,
    emitter: Emitter
  ): void
{
  for (const node of nodes) {
    if (!isElement(node)) {
      continue;
    }

    emitElement(
      node,
      scope,
      depth,
      emitter);
  }
}

/**
 * Emits the checks for one element and its descendants, in the order the
 * runtime binds them: the element's own bindings read `scope`, and with
 * `data-bind-context` its descendants read the context value instead.
 */
function emitElement(
    element: ParsedElement,
    scope: string,
    depth: number,
    emitter: Emitter
  ): void
{
  let contextPath: string | null = null;

  for (const attribute of element.attrs) {
    if (!attribute.name.startsWith(BIND_PREFIX)) {
      continue;
    }

    if (attribute.name === CONTEXT_ATTR) {
      contextPath = attribute.value;

      continue;
    }

    const suffix =
      attribute.name.slice(
        BIND_PREFIX.length);

    if (
      suffix.startsWith('on')
      && !isEventSuffix(suffix)
    ) {
      throw errorAt(
        element,
        attribute.name,
        emitter.sourceName,
        `'${attribute.name}' is not a binding; event bindings are written `
          + 'data-bind-on-<event>, for example data-bind-on-click.');
    }

    let spec: BindingSpec;

    try {
      spec =
        createBindingSpec(
          suffix,
          attribute.value);
    } catch (error) {
      throw errorAt(
        element,
        attribute.name,
        emitter.sourceName,
        (error as Error).message);
    }

    emitBinding(
      element,
      attribute.name,
      spec,
      scope,
      depth,
      emitter);
  }

  // Content of a nested <template> is inert: the runtime does not bind it.
  if (element.tagName === 'template') {
    return;
  }

  if (
    contextPath === null
    || contextPath.trim() === ''
  ) {
    if (contextPath !== null) {
      checkPath(
        element,
        CONTEXT_ATTR,
        contextPath,
        emitter);
    }

    emitChildren(
      element.childNodes,
      scope,
      depth,
      emitter);

    return;
  }

  checkPath(
    element,
    CONTEXT_ATTR,
    contextPath,
    emitter);

  const context =
    `context${++emitter.contexts}`;

  const indent =
    '  '.repeat(depth);

  if (emitter.lines.length > 0) {
    emitter.lines.push('');
  }

  emitter.lines.push(
    `${indent}const ${context} =`,
    `${indent}  ${
      pathExpression(
        scope,
        contextPath)
    };${
      comment(
        element,
        CONTEXT_ATTR,
        emitter)
    }`,
    '',
    `${indent}if (`,
    `${indent}  ${context} !== null`,
    `${indent}  && ${context} !== undefined`,
    `${indent}) {`);

  emitChildren(
    element.childNodes,
    context,
    depth + 1,
    emitter);

  emitter.lines.push(
    `${indent}}`);
}

function emitBinding(
    element: ParsedElement,
    attributeName: string,
    spec: BindingSpec,
    scope: string,
    depth: number,
    emitter: Emitter
  ): void
{
  const indent =
    '  '.repeat(depth);

  const note =
    comment(
      element,
      attributeName,
      emitter);

  if (spec.kind === 'event') {
    if (spec.actionPath === '') {
      return;
    }

    emitter.usesAction = true;

    emitter.lines.push(
      `${indent}void (${
        pathExpression(
          scope,
          spec.actionPath)
      } satisfies Action);${note}`);

    return;
  }

  for (const pipe of spec.pipes) {
    emitter.usesPipeName = true;

    emitter.lines.push(
      `${indent}void (${JSON.stringify(pipe.name)} satisfies PipeName);${note}`);
  }

  if (spec.path === '') {
    return;
  }

  const value =
    pathExpression(
      scope,
      spec.path);

  // A pipe returns unknown, so after one only the path itself is checked.
  if (spec.pipes.length > 0) {
    emitter.lines.push(
      `${indent}void ${value};${note}`);

    return;
  }

  switch (spec.target.kind) {
    case 'text':
    case 'html':
    case 'class':
      emitter.lines.push(
        `${indent}void ${value};${note}`);

      return;

    case 'attr':
      emitter.usesAttributeValue = true;

      emitter.lines.push(
        `${indent}void (${value} satisfies AttributeValue);${note}`);

      return;

    case 'prop':
      emitter.lines.push(
        `${indent}void (${value} satisfies TemplateElement<${
          JSON.stringify(element.tagName)
        }>[${JSON.stringify(spec.target.name)}] | null | undefined);${note}`);

      return;
  }
}

/**
 * The expression that reads `path` from `scope`. Every segment after the first
 * is read with `?.`, because a path that does not resolve is not an error at
 * run time, while a property the type does not have is still one here.
 */
function pathExpression(
    scope: string,
    path: string
  ): string
{
  const segments =
    splitPath(path);

  let expression = scope;

  segments.forEach(
    (
        segment,
        index
      ) =>
    {
      const optional = index > 0;

      if (IDENTIFIER.test(segment)) {
        expression += `${
          optional
            ? '?.'
            : '.'
        }${segment}`;
      } else if (/^\d+$/.test(segment)) {
        expression += `${
          optional
            ? '?.'
            : ''
        }[${segment}]`;
      } else {
        expression += `${
          optional
            ? '?.'
            : ''
        }[${JSON.stringify(segment)}]`;
      }
    });

  return expression;
}

function checkPath(
    element: ParsedElement,
    attributeName: string,
    path: string,
    emitter: Emitter
  ): void
{
  try {
    splitPath(path);
  } catch (error) {
    throw errorAt(
      element,
      attributeName,
      emitter.sourceName,
      (error as Error).message);
  }
}

function comment(
    element: ParsedElement,
    attributeName: string,
    emitter: Emitter
  ): string
{
  const location =
    element.sourceCodeLocation?.attrs?.[attributeName];

  const position =
    location
    ? `:${location.startLine}:${location.startCol}`
    : '';

  return ` // ${emitter.fileName}${position} ${attributeName}`;
}

function errorAt(
    element: ParsedElement,
    attributeName: string | undefined,
    fileName: string,
    reason: string
  ): TemplateCompileError
{
  const location =
    element.sourceCodeLocation;

  const attributeLocation =
    attributeName === undefined
    ? undefined
    : location?.attrs?.[attributeName];

  const line =
    attributeLocation?.startLine
    ?? location?.startLine
    ?? 1;

  const column =
    attributeLocation?.startCol
    ?? location?.startCol
    ?? 1;

  return new TemplateCompileError(
    reason,
    fileName,
    line,
    column);
}

function isElement(
    node: ParsedNode
  ): node is ParsedElement
{
  return 'tagName' in node;
}

function baseName(
    fileName: string
  ): string
{
  return fileName.split(/[\\/]/).pop() ?? fileName;
}

interface ModuleParts
{
  fileName: string;
  runtimeModule: string;
  model: TypeReference;
  pipes: TypeReference | null;
  html: string;
  emitter: Emitter;
}

function renderModule(
    parts: ModuleParts
  ): string
{
  const { emitter, model, pipes } = parts;

  const lines: string[] =
    [ `${GENERATED_HEADER} from ${parts.fileName}. Do not edit.`,
      `import { bindDataModel,`,
      `         type BindDataModelOptions }`,
      `  from ${JSON.stringify(parts.runtimeModule)};`,
      `import type { ${model.name} as TemplateModel }`,
      `  from ${JSON.stringify(model.specifier)};` ];

  if (pipes !== null) {
    lines.push(
      `import type { ${pipes.name} as TemplatePipes }`,
      `  from ${JSON.stringify(pipes.specifier)};`);
  }

  const optionsType =
    pipes === null
    ? 'options?: BindDataModelOptions'
    : 'options: BindDataModelOptions & { pipes: TemplatePipes; }';

  lines.push(
    '',
    "/** The markup inside the template's <template> element. */",
    'export const html =',
    `  ${JSON.stringify(parts.html)};`,
    '',
    'export function createTemplate(',
    '    doc: Document = document',
    '  ): HTMLTemplateElement',
    '{',
    '  const template =',
    "    doc.createElement('template');",
    '',
    '  template.innerHTML = html;',
    '',
    '  return template;',
    '}',
    '',
    'export function bindTemplate(',
    '    root: ParentNode,',
    '    model: TemplateModel,',
    `    ${optionsType}`,
    '  ): () => boolean',
    '{',
    '  return bindDataModel(',
    '    root,',
    '    model,',
    '    options);',
    '}',
    '',
    '// A tag the DOM types do not declare, such as an undeclared custom element,',
    '// takes any property.',
    'type TemplateElement<K extends string> =',
    '  K extends keyof HTMLElementTagNameMap',
    '  ? HTMLElementTagNameMap[K]',
    '  : HTMLElement & Record<string, unknown>;');

  if (emitter.usesAttributeValue) {
    lines.push(
      '',
      'type AttributeValue = string | number | boolean | null | undefined;');
  }

  if (emitter.usesAction) {
    lines.push(
      '',
      'type Action = ((...args: never[]) => unknown) | null | undefined;');
  }

  if (emitter.usesPipeName) {
    const names =
      Object.keys(
        createBuiltInPipes())
      .map(
        name => JSON.stringify(name));

    if (pipes !== null) {
      names.push(
        '(keyof TemplatePipes & string)');
    }

    lines.push(
      '',
      'type PipeName =',
      ...names.map(
        name => `  | ${name}`),
      '  ;');
  }

  lines.push(
    '',
    '// Never called: each statement checks one binding against the model and',
    '// element types, and names the template line it comes from.',
    'function check(',
    '    model: TemplateModel',
    '  ): void',
    '{',
    ...emitter.lines,
    '}',
    '',
    'void check;',
    '');

  return lines.join('\n');
}
